djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('pizza/', include('pizza.urls')),
    path('studenci/', include('studenci.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

pizza/urls.py
from django.urls import path

from . import views
app_name = 'pizza'
urlpatterns = [
    path('', views.index, name='index'),
    path('news/', views.news, name='news'),
    path('gallery/', views.gallery, name='gallery'),
    path('pizze/', views.pizze, name='pizze'),
]

studenci/urls.py
from django.urls import path

from . import views

app_name = 'studenci'
urlpatterns = [
	path('', views.index, name='index'),
    path('miasta/', views.miasta, name='miasta'),
    path('uczelnie/', views.uczelnie, name='uczelnie'),
    path('login/', views.login, name='login'),
]

users/urls.py
from django.urls import path

from . import views
app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('rejestruj/', views.rejestruj, name='rejestruj'),
    path('loguj/', views.loguj, name='loguj'),
    path('wyloguj/', views.wyloguj, name='wyloguj'),
]

pizza/models.py
from django.db import models


class Pizza(models.Model):
    LARGE = 'L'
    MEDIUM = 'M'
    SMALL = 'S'
    ROZMIARY = (
        (LARGE, 'duza'),
        (MEDIUM, 'srednia'),
        (SMALL, 'mala'),
    )

    nazwa = models.CharField(
        verbose_name='pizza',
        max_length=30,
        help_text='Nazwa pizzy')
    opis = models.TextField(
        blank=True,
        default='',
        help_text='Opis pizzy')

    rozmiar = models.CharField(max_length=1,
                               choices=ROZMIARY,
                               default=LARGE)

    cena = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    data = models.DateField('dodano', auto_now_add=True)

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "pizze"

class Skladnik(models.Model):
    pizze = models.ManyToManyField(Pizza, related_name='skladniki', null=True, blank=True)
    nazwa = models.CharField('skladnik', max_length=30)
    jarski = models.BooleanField(
        'jarski?',
        help_text='Zaznacz, jeżeli składnik jest odpowiedni dla wegetarian',
        default=False
    )
    cena = models.DecimalField(max_digits=3, decimal_places=2, default=0)

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "skladniki"

studenci/models.py
from django.db import models

class Uczelnia(models.Model):
    nazwa = models.CharField(verbose_name='uczelnia', max_length=30)

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "uczelnie"

class Miasto(models.Model):
    nazwa = models.CharField(verbose_name='miasto', max_length=30)
    kod = models.CharField(max_length=30, help_text="Wpisz kod pocztowy")

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "miasta"

class Student(models.Model):
    imie = models.CharField(max_length=30)
    nazwisko = models.CharField(max_length=30)
    uczelnia = models.ForeignKey(Uczelnia, on_delete=models.SET_NULL, null=True)
    miasto = models.ForeignKey(Miasto, on_delete=models.SET_NULL, null=True)
    roks = models.CharField(max_length=3, blank=True, default='')
    dochod = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "studenci"

users/models.py
from django.db import models

# Create your models here.

studenci/forms.py
from django import forms


class StudentLoginForm(forms.Form):
    login = forms.CharField(
        label="Twój login:",
        max_length=25,
        widget=forms.TextInput()
    )


class UczelniaForm(forms.Form):
    nazwa = forms.CharField(
        label="Nazwa uczelni:",
        max_length=30,
        widget=forms.TextInput()
    )

class MiastoForm(forms.Form):
    nazwa = forms.CharField(
        label="Nazwa miasta:",
        max_length=30,
        widget=forms.TextInput()
    )
    kod = forms.CharField(
        label="Kod pocztowy:",
        max_length=6,
        widget=forms.TextInput()
    )

users/forms.py
from django import forms

class UserLoginForm(forms.Form):
    login = forms.CharField(
        label="Twój login:",
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    haslo = forms.CharField(
        label="Twoje hasło:",
        max_length=30,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password'})
    )

pizza/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'pizza/index.html')

def news(request):
    return render(request, 'pizza/news.html')

def gallery(request):
    return HttpResponse("Witaj w galerii")

def pizze(request):
    return render(request, 'pizza/pizze.html')

studenci/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse

from studenci.models import Miasto, Uczelnia
from studenci.forms import StudentLoginForm, UczelniaForm, MiastoForm


def index(request):
    #return HttpResponse("Witaj w aplikacji Studenci!")
    return render(request, 'studenci/index.html')


def miasta(request):
    if request.method == 'POST':
        form = MiastoForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            m = Miasto(nazwa=form.cleaned_data['nazwa'], kod=form.cleaned_data['kod'])
            m.save()
            messages.success(request, "Dane zapisano!")
            return redirect(reverse('studenci:miasta'))
    else:
        form = MiastoForm()
    miasta = Miasto.objects.all()
    kontekst = {
        'miasta': miasta,
        'form': form
    }

    return render(request, 'studenci/miasta.html', kontekst)


def uczelnie(request):

    if request.method == 'POST':
        form = UczelniaForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            u = Uczelnia(nazwa=form.cleaned_data['nazwa'])
            u.save()
            messages.success(request, "Dane zapisano!")
            # przekierowanie
            return redirect(reverse('studenci:uczelnie'))
    else:
        form = UczelniaForm()

    uczelnie = Uczelnia.objects.all()
    kontekst = {
        'form': form,
        'uczelnie': uczelnie
    }

    if request.user.has_perm('studenci.add_uczelnia'):
        return render(request, 'studenci/uczelnie.html', kontekst)
    else:
        messages.info(request, "Nie możesz dodawać uczelni.")
        return redirect(reverse('studenci:index'))


def login(request):
    if request.method == 'POST':
        pass
    else:
        form = StudentLoginForm()

    kontekst = { 'form': form }
    return render(request, 'studenci/login.html', kontekst)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.urls import reverse
from users.forms import UserLoginForm
from django.contrib.auth import authenticate, login, logout

def index(request):
    return render(request, 'users/index.html')

def wyloguj(request):
    logout(request)
    messages.info(request, "Zostałeś wylogowany!")
    return redirect(reverse('users:index'))

def rejestruj(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Konto utworzono!")
            return redirect(reverse('studenci:miasta'))
    else:
        form = UserCreationForm()

    kontekst = {'form': form}
    return render(request, 'users/rejestruj.html', kontekst)


def loguj(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            nazwa = form.cleaned_data['login']
            haslo = form.cleaned_data['haslo']
            user = authenticate(request, username=nazwa, password=haslo)
            if user is not None:
                login(request, user)
                messages.success(request, "Zostałeś zalogowany!")
                return redirect(reverse('users:index'))
            else:
                messages.error(request, "Błędny login lub hasło!")
    else:
        form = UserLoginForm()

    kontekst = {'form': form}
    return render(request, 'users/loguj.html', kontekst)

pizza/templates/pizza/index.html
{% extends 'szablon.html' %}
{% block naglowek %}Pizza{% endblock naglowek %}

{% block tresc %}
    <p>Oferujemy szeroki wybór pizz i nie tylko!</p>
{% endblock tresc %}

pizza/templates/pizza/news.html
{% extends 'szablon.html' %}
{% block tytul %}Pizza{% endblock tytul %}
{% block naglowek %}Nowości!{% endblock naglowek %}

{% block tresc %}
    <p>Nowe pizze</p>
{% endblock tresc %}

pizza/templates/pizza/pizze.html
{% extends 'szablon.html' %}

{% block naglowek %}Pizze{% endblock naglowek %}

{% block tresc %}
<h2>Dodaj pizze</h2>
<form action="." method="POST">
    {% csrf_token %}
    <input type="text" name="nazwa" maxlength="30">
    <br>
    <input type="text" name="opis" maxlength="6">
    <br>
    <input type="text" name="rozmiar" maxlength="6">
    <br>
    <input type="text" name="cena" maxlength="6">
    <br>
    <input type="text" name="data" maxlength="6">
    <br>
    <input type="submit" value="Zapisz">
</form>

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/index.html
{% extends 'szablon.html' %}
{% block naglowek %}Studenci{% endblock naglowek %}

{% block tresc %}
    <p>Witaj wśród studentów!</p>
{% endblock tresc %}

studenci/templates/studenci/login.html
{% extends 'szablon.html' %}
{% block naglowek %}Studenci – Logowanie{% endblock naglowek %}

{% block tresc %}

<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>

{% endblock tresc %}

studenci/templates/studenci/miasta.html
{% extends 'szablon.html' %}

{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
<h2>Dodaj miasto</h2>
    {% if user.is_authenticated %}
        {% if perms.studenci.add_miasto %}
            <form action="." method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Zapisz">
            </form>
        {% else %}
            <div class="well">Nie możesz dodawać miast!</div>
        {% endif %}
    {% endif %}

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/uczelnie.html
{% extends 'szablon.html' %}
{% block naglowek %}Uczelnie{% endblock naglowek %}

{% block tresc %}
<h1>Uczelnie</h1>

<h2>Dodaj uczelnię</h2>
<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>

<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tytul %}Projekt Django{% endblock tytul %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-sm bg-light">
        <a class="navbar-brand" href="http://lo1.sandomierz.pl">I LO CG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Pizza</a>
                <div class="dropdown-menu">
                    <a href="{% url 'pizza:index' %}" class="dropdown-item">Strona główna</a>
                    <a href="{% url 'pizza:news' %}" class="dropdown-item">Nowości</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Studenci</a>
                <div class="dropdown-menu">
                    <a href="{% url 'studenci:index' %}" class="dropdown-item">Strona główna</a>
                    <a href="{% url 'studenci:login' %}" class="dropdown-item">Login</a>
                    <a href="{% url 'studenci:miasta' %}" class="dropdown-item">Miasta</a>
                    <a href="{% url 'studenci:uczelnie' %}" class="dropdown-item">Uczelnie</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Użytkownicy</a>
                <div class="dropdown-menu">
                    <a href="{% url 'users:rejestruj' %}" class="dropdown-item">Rejestracja</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:wyloguj' %}" class="dropdown-item">Wyloguj</a>
                    {% else %}
                        <a href="{% url 'users:loguj' %}" class="dropdown-item">Logowanie</a>
                    {% endif %}
                </div>
            </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col">

    <h1>{% block naglowek %}Aplikacja Django{% endblock naglowek %}</h1>

    {% if messages %}
    <ul>
        {% for komunikat in messages %}
        <li>{{ komunikat }}</li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Brak komunikatów.</p>
    {% endif %}

    {% block tresc %}{% endblock tresc %}

            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

users/templates/users/index.html
{% extends 'szablon.html' %}
{% block tytul %}Strona głowna{% endblock tytul %}
{% block naglowek %}Uzytkownicy{% endblock naglowek %}
{% block tresc %}
    <a>Witaj wsród użytkowników!</a>
{% endblock tresc %}

users/templates/users/loguj.html
{% extends 'szablon.html' %}
{% block tytul %}Użytkownicy{% endblock tytul %}
{% block naglowek %}Logowanie{% endblock naglowek %}
{% block tresc %}

    {% if user.is_authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}!</p>
    {% else %}
        {{ form.errors }}
        <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zaloguj" class="btn btn-primary">
        </form>
    {% endif %}

{% endblock tresc %}

users/templates/users/rejestruj.html
{% extends 'szablon.html' %}
{% block tytul %}Użytkownicy{% endblock tytul %}
{% block naglowek %}Rejestracja{% endblock naglowek %}

{% block tresc %}
    {% if user.is.authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}</p>
    {% else %}
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Zapisz" class="btn">
        </form>
    {% endif %}
{% endblock tresc %}